#!/usr/bin/with-contenv bash

# make folders if required
mkdir -p \
	"$DATADIR" \
  /config/log/mysql \
  /var/log/mysql \
  /var/run/mysqld

chown -R abc:abc /var/log/mysql
chmod -R 777 /var/log/mysql

CONF_FILE="/etc/my.cnf";

# configure my.cnf and mysqld_safe
sed -ri 's/^(bind-address|skip-networking)/;\1/' "/etc/my.cnf.d/mariadb-server.cnf"
sed -i "s/user='mysql'/user='abc'/g" /usr/bin/mysqld_safe


# setup custom cnf file
[[ ! -f /config/custom.cnf ]] && \
	cp /defaults/my.cnf /config/custom.cnf
[[ ! -L /etc/my.cnf.d/custom.cnf && -f /etc/my.cnf.d/custom.cnf ]] && \
	rm /etc/my.cnf.d/custom.cnf
[[ ! -L /etc/my.cnf.d/custom.cnf ]] && \
	ln -s /config/custom.cnf /etc/my.cnf.d/custom.cnf

# setup the log to stderr
if [ -z "$LOG_TO_FILE" ]; then
  ln -sf /dev/stdout /var/log/mysql/error.log
  sed -i 's%/config/log/mysql/error.log%/var/log/mysql/error.log%g' /config/custom.cnf
  echo "**** Log to Console Enable ****"
else
  sed -i 's%/var/log/mysql/error.log%/config/log/mysql/error.log%g' /config/custom.cnf
  echo "**** Log to File Enable ****"
fi

# set permissions
chmod -R 777 \
	/var/run/mysqld
